import json
from packet import Packet
from router import Router


class DVrouter(Router):

    def __init__(self, addr, heartbeat_time):
        Router.__init__(self, addr)
        self.heartbeat_time = heartbeat_time
        self.last_time = 0
        
        self.distance = {}               # dest -> cost: chi phí đến từng đích: { "X": 5, "Y": 3, ... }
        self.nexthop = {}                # dest -> next hop: đến đích nào thì đi qua cổng nào: { "X": port_số_2, "Y": port_số_1, ... }
        self.neighbors = {}              # neighbor -> cost: cổng nào nối đến neighbor nào với chi phí bao nhiêu: { port_số_1: ("A", 2), port_số_2: ("B", 5), ... }
        self.neighbor_dvs = {}           # neighbor -> {dest: cost}: neighbor nào gửi đến mình DV gì: { "A": {"X": 5, "Y": 3, ...}, "B": {"X": 2, "Z": 4, ...}, ... }

        self.distance[self.addr] = 0
        pass

    def handle_packet(self, port, packet):
        """Process incoming packet."""

        if packet.is_traceroute:
            # Hint: this is a normal data packet
            # If the forwarding table contains packet.dst_addr
            #   send packet based on forwarding table, e.g., self.send(port, packet)

            dest = packet.dst_addr
            if dest == self.addr:
                pass
            elif dest in self.nexthop:
                self.send(self.nexthop[dest], packet)
            pass
        else:
            # Hint: this is a routing packet generated by your routing protocol
            # If the received distance vector is different
            #   update the local copy of the distance vector
            #   update the distance vector of this router
            #   update the forwarding table
            #   broadcast the distance vector of this router to neighbors

            neighbor_dv = json.loads(packet.content)
            neighbor_addr = packet.src_addr
            self.neighbor_dvs[neighbor_addr] = neighbor_dv

            old_distance = self.distance.copy()
            old_nexthop = self.nexthop.copy()
            self.run_bellman_ford()

            if self.distance != old_distance:
                self.send_dv_to_neighbors()                                     # Nếu DV của chính mình thay đổi, broadcast DV mới đến neighbors
            pass

    def handle_new_link(self, port, endpoint, cost):
        """Handle new link."""
        # TODO
        #   update the distance vector of this router
        #   update the forwarding table
        #   broadcast the distance vector of this router to neighbors

        self.neighbors[port] = (endpoint, cost)

        # LUÔN chạy lại Bellman-Ford và broadcast, dù link mới có ngắn hơn hay không
        # Lý do: láng giềng mới có thể biết đường đến các đích khác mà mình chưa biết
        # → phải tính lại và thông báo cho tất cả láng giềng trong mọi trường hợp
        self.run_bellman_ford()
        self.send_dv_to_neighbors()
        pass

    def handle_remove_link(self, port):
        """Handle removed link."""
        # TODO
        #   update the distance vector of this router
        #   update the forwarding table
        #   broadcast the distance vector of this router to neighbors

        if port not in self.neighbors:
            return
        neighbor_addr = self.neighbors[port][0]
        del self.neighbors[port]
        if neighbor_addr in self.neighbor_dvs:
            del self.neighbor_dvs[neighbor_addr]                                        # Xóa DV của neighbor bị mất khỏi self.neighbor_dvs
        self.run_bellman_ford()                                                         # Cập nhật DV của chính mình vì mất link
        self.send_dv_to_neighbors()                                                     # Broadcast DV mới đến neighbors
        pass

    def handle_time(self, time_ms):
        """Handle current time."""
        if time_ms - self.last_time >= self.heartbeat_time:
            self.last_time = time_ms
            # TODO
            #   broadcast the distance vector of this router to neighbors

            self.send_dv_to_neighbors()                                                     # Broadcast DV của chính mình đến neighbors định kỳ
            pass

    def __repr__(self):
        """Representation for debugging in the network visualizer."""
        # TODO
        #   NOTE This method is for your own convenience and will not be graded
        return f"DVrouter(addr={self.addr}, distance={self.distance})"

    def send_dv_to_neighbors(self):
        for port, (neighbor, _) in self.neighbors.items():
            dv_to_send = {}                                                           # Tạo bảng DV để gửi đi
            for dest, dist in self.distance.items():
                if dest in self.nexthop and self.nexthop[dest] == port:               # Nếu đích này đi qua neighbor này, áp dụng poison reverse
                    dv_to_send[dest] = 16
                else:
                    dv_to_send[dest] = dist

            content = json.dumps(dv_to_send)                                          # Chuyển DV thành JSON string để gửi đi
            packet = Packet(Packet.ROUTING, self.addr, neighbor, content)             # Tạo packet routing chứa DV
            self.send(port, packet)

    def run_bellman_ford(self):
        """Cập nhật bảng DV mới khi có thông tin mới từ neighbor hoặc link."""
        new_distance = {self.addr: 0}                                                 # DV mới bắt đầu với chi phí đến chính mình là 0
        new_next_hop = {}

        for port, (neighbor, link_cost) in self.neighbors.items():
            if neighbor not in self.neighbor_dvs:                                     # Nếu neighbor này chưa gửi DV nào, bỏ qua
                continue
            for dest, neighbor_cost in self.neighbor_dvs[neighbor].items():
                if neighbor_cost >= 16:
                    continue
                new_cost = link_cost + neighbor_cost
                if new_cost >= 16:
                    continue
                if dest not in new_distance or new_cost < new_distance[dest]:
                    new_distance[dest] = new_cost
                    new_next_hop[dest] = port

        for port, (neighbor, link_cost) in self.neighbors.items():
            if neighbor not in new_distance or link_cost < new_distance[neighbor]:     # Cập nhật chi phí đến neighbor trực tiếp nếu tốt hơn
                new_distance[neighbor] = link_cost
                new_next_hop[neighbor] = port

        self.distance = new_distance
        self.nexthop = new_next_hop